### ISSUE TITLE
status page "blue errors"

### ISSUE THREAD

**Issue by nwgat** [BotoX/ServerStatus#10]
would been useful to not show this error and just wait for next update, show last update instead of  erroring out the whole page

![](http://i.imgur.com/8Vrn0cF.png)

i really like your monitoring tool, its simple, fast and elegant

**Comment by BotoX** [comment]
serverstatus.js line 248
```javascript
	}).fail(function(update_error) {
		if (!error) {
			$("#servers > tr.accordion-toggle").each(function(i) {
```
Change if (!error) to if (false) and the data won't be overwritten, the Last updated label at the bottom will still show Update error.

I like it the error way better :v since it's easy to change I'm gonna leave it like this, okay?

**Comment by nwgat** [comment]
perhaps put a note in the readme and you can close this issue :)
