### ISSUE TITLE
Windows executable path no longer valid

### ISSUE THREAD

**Issue by coonsmatthew** [BotoX/ServerStatus#12]
I'm walking through the install guide and I was attempting to download the pre-compiled Windows client, but I'm getting a 404 page not found error here: https://i.botox.bz/serverstatus-client.exe

**Comment by BotoX** [comment]
Ooops, currently not at home, but this should work: https://github.com/BotoX/ServerStatus/blob/a8963041329fd3a1d84649422bfe679309da446d/clients/windows/client.exe?raw=true

**Comment by coonsmatthew** [comment]
Thank You!
