### ISSUE TITLE
Python psutil client does not work on Windows

### ISSUE THREAD

**Issue by coonsmatthew** [BotoX/ServerStatus#13]
Hello, 

Me again. I'm trying to get the client-psutil.py script working on Windows OS. 

I'm running it on Python 2.7.10 and have the psutil x86 package installed. I've filled in the client details and attempt to execute the python script. I've noticed two errors: 

1. The `psutil.BOOT_TIME` called out on line 21 has been renamed `psutil.boot_time`. I was able to quickly fix this issue. 
2. When I attempt to execute the script, I get a recurring error: 

('Caught Exception:', TypeError("unsupported operand type(s) for -: 'float' and
'function'",))
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

('Caught Exception:', TypeError("unsupported operand type(s) for -: 'float' and
'function'",))
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

Traceback (most recent call last):
  File "client-psutil.py", line 131, in <module>
    CPU = get_cpu()
  File "client-psutil.py", line 56, in get_cpu
    return psutil.cpu_percent(interval=INTERVAL)
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 1455, in cpu_per
cent
    time.sleep(interval)
KeyboardInterrupt

- At the end you see me killing the recurring error, however it does seem like the client connects for a second before dropping off each time the error cycles.

**Comment by BotoX** [comment]
I am guessing the new psutil.boot_time is a function so you have to write it like this: psutil.boot_time()
See here: https://pythonhosted.org/psutil/

**Comment by coonsmatthew** [comment]
Thank you, 

That worked like a charm. 

I changed line 21 to: 
	`return int(time.time() - psutil.boot_time())`

**Comment by ehab2012** [comment]
i also confirm  psutil.boot_time() should be updated if not already in master. Thanks  BotoX and best wishes from me.
