### ISSUE TITLE
Cannot add more then 32 servers

### ISSUE THREAD

**Issue by coonsmatthew** [BotoX/ServerStatus#14]
I'm adding servers to the config.json file and when I hit server number 33 new servers stopped showing up on the monitoring page after I restarted the sergate process. 

Is there a limitation to the number of servers that can be added with this monitoring tool? 

Thanks

**Comment by BotoX** [comment]
https://github.com/BotoX/ServerStatus/blob/master/server/src/network.h#L13
```C
NET_MAX_CLIENTS = 32
```

And obviously recompile and restart the server.
I wouldn't have thought somebody will be using this for this many servers :o

**Comment by coonsmatthew** [comment]
Thank you! I just upped the max clients config and recompiled the server and everything's working great. Glad that I could stretch the limits :)

**Comment by coonsmatthew** [comment]
Closing issue.

**Comment by cfgalvani** [comment]
@coonsmatthew Did it run smoothly with 32+ clients? How many clients have you tried so far? 100+ ?
