### ISSUE TITLE
I have a problem SpeedRx=(3.21949e+10-3.21949e+10)/1

### ISSUE THREAD

**Issue by jimmyr57000** [BotoX/ServerStatus#15]
Hello, 

I have a problem during client launch

(root@FC02) (/home) # ./serverstatus-client.sh

Connected.

./serverstatus-client.sh: ligne 121: let: SpeedRx=(3.21949e+10-3.21949e+10)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".21949e+10-3.21949e+10)/1")
./serverstatus-client.sh: ligne 122: let: SpeedTx=(1.45228e+11-1.45228e+11)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".45228e+11-1.45228e+11)/1")
./serverstatus-client.sh: ligne 121: let: SpeedRx=(3.2195e+10-3.21949e+10)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".2195e+10-3.21949e+10)/1")
./serverstatus-client.sh: ligne 122: let: SpeedTx=(1.45229e+11-1.45228e+11)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".45229e+11-1.45228e+11)/1")
./serverstatus-client.sh: ligne 121: let: SpeedRx=(3.21952e+10-3.2195e+10)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".21952e+10-3.2195e+10)/1")
./serverstatus-client.sh: ligne 122: let: SpeedTx=(1.45229e+11-1.45229e+11)/1 : erreur de syntaxe : opérateur arithmétique non valable (le symbole erroné est ".45229e+11-1.45229e+11)/1")

( My debian is language french )

Thanks, !

**Comment by BotoX** [comment]
Could you run these two commands and post the output:

`grep ":" /proc/net/dev | grep -v -e "lo" -e "tun" | awk '{a+=$2}{b+=$10}END{print a,b}'`

`grep ":" /proc/net/dev | grep -v -e "lo" -e "tun" | awk -M '{a+=$2}{b+=$10}END{printf "%s %s", a,b}'`

**Comment by jimmyr57000** [comment]
Hello, 

3.40579e+10 1.52567e+11

awk: not an option: -M

**Comment by BotoX** [comment]
Okay, I guess your awk isn't recent enough for -M (--bignums).
You can try without, should be fine as long as the number doesn't become too big:
`grep ":" /proc/net/dev | grep -v -e "lo" -e "tun" | awk '{a+=$2}{b+=$10}END{printf "%s %s", a,b}'`

**Comment by jimmyr57000** [comment]
3.476e+10 1.55714e+11(

Screen commande ssh : http://prntscr.com/apr2fb

**Comment by BotoX** [comment]
I can't reproduce this on my system actually.
Could you try again but do this before:
`export LC_NUMERIC="C"`
maybe this one changes the behaviour too?:
`export LC_COLLATE="C"`

**Comment by jimmyr57000** [comment]
I change it to any place?

Sorry, I do not understand English very well I'm french.

**Comment by BotoX** [comment]
Just do:

```
export LC_NUMERIC="C"
export LC_COLLATE="C"
```

and try if it works after that.

**Comment by dausruddin** [comment]
I stumbled upon this same issue.
Seems that this is issue where bash version doesnt support arithmetic calculation. I can confirm about this because I have 2 servers running Debian 7 and Ubuntu 12.04 and both have bash version 4.2.xx as the latest version. While my another debian 8 and ubuntu 14.04 servers have version 4.3.xx

So the solution is to use python, or upgrade bash version to 4.3.xx
