### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by wenxhwork** [BotoX/ServerStatus#17]
I set up and kept all the settings default. And the data refresh every 5 or more seconds,but the demo page seems to be realtime. How to configure?

**Comment by BotoX** [comment]
The default update interval is 2 seconds for the webpage.
The clients report data every seconds by default.

Maybe your webserver/browser/cloudflare is caching the json response?
Check the headers on /json/stats.json

**Comment by wenxhwork** [comment]
Hi ,
I checked the header and found that there many 304 Not Modified. I compared your demo and all your status of stats.json are 200. I thought it was gzip to blame,but after I disabled it,the 304 still exist. My webserver is nginx.
Here is the header.

> HTTP/1.1 304 Not Modified
> Server: nginx
> Date: Thu, 28 Jul 2016 08:27:35 GMT
> Last-Modified: Thu, 28 Jul 2016 08:27:08 GMT
> Connection: keep-alive
> ETag: "5799c1dc-9e5"
> Expires: Thu, 28 Jul 2016 08:27:34 GMT
> Cache-Control: no-cache
> Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
> Cache-Control: no-cache
> 
> GET`/json/stats.json HTTP/1.1
> Host: ***.com
> Connection: keep-alive
> Authorization: Basic d2VueGh3b3JrOjk1Y094Y294
> Accept: application/json, text/javascript, */*; q=0.01
> X-Requested-With: XMLHttpRequest
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
> Referer: https://***.com/
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: zh-CN,zh;q=0.8
> Cookie: style=light
> If-None-Match: W/"5799c1dc-9e5"
> If-Modified-Since: Thu, 28 Jul 2016 08:27:08 GMT`

**Comment by BotoX** [comment]
Does your filesystem have modified date metadata turned off maybe?
You should check if the file modified actually changes (just spam ls -l every second in your terminal)

> Date: Thu, 28 Jul 2016 08:27:35 GMT
> Last-Modified: Thu, 28 Jul 2016 08:27:08 GMT

Looks like your file isn't being written to very often..
Though the server sleeps 1 second and then writes the new file: https://github.com/BotoX/ServerStatus/blob/master/server/src/main.cpp#L268

**Comment by def-** [comment]
It's also possible that something in the script blocks for a few seconds. For example if you have a network file system mounted, each call to `df` can take a few seconds.

**Comment by BotoX** [comment]
The server will write a new stats.json every second nonetheless.
https://github.com/BotoX/ServerStatus/blob/master/server/src/main.cpp#L202

**Comment by wenxhwork** [comment]
Sorry for the late update. I changed the host server and the problem solved. I guess it maybe the network problem.
