### ISSUE TITLE
precompiled exe

### ISSUE THREAD

**Issue by malikkal** [BotoX/ServerStatus#18]
The precompiled exe is not available at https://i.botox.bz/serverstatus-client.exe. Can help fix, please?

**Comment by malikkal** [comment]
Sorted it using pyinstaller instead pf py2exe.

**Comment by BotoX** [comment]
Since you've made an .exe yourself, (I was gonna do it but my windows VM just died after an update...), could you post it here in case anyone else needs it?

**Comment by IIPoliII** [comment]
Same i can't get it to work could you post the .exe?

**Comment by IIPoliII** [comment]
You can find a package here with the 3 files needed : http://scripts.poli.network/Github/ServerStatus/client.zip
Note that you need to put your config in client.cfg and then simply run it.
