### ISSUE TITLE
windows .exe file

### ISSUE THREAD

**Issue by rupe** [BotoX/ServerStatus#2]
Not so much an issue as a request. Could you just link to the clients/windows/client.exe file instead of including it in the repo? That file alone accounts for more than half the size of your repository, and I would imagine only a small percent of ServerStatus users would be using it..of course I could be wrong :)

Thanks

**Comment by IIPoliII** [comment]
You can find a package here with the 3 files needed : http://scripts.poli.network/Github/ServerStatus/client.zip
Note that you need to put your config in client.cfg and then simply run it.
