### ISSUE TITLE
Only the first 30 nodes are displayed

### ISSUE THREAD

**Issue by jialezi666** [BotoX/ServerStatus#25]
I have a lot of nodes, but only show the first 30 nodes, how to modify

**Comment by kmm996** [comment]
show only the first 32 nodes,no 30

**Comment by jialezi666** [comment]
not 30,  only show the first 32 nodes,

**Comment by BotoX** [comment]
https://github.com/BotoX/ServerStatus/blob/master/server/src/network.h

NET_MAX_CLIENTS
set it higher and recompile.

**Comment by jialezi666** [comment]
thx,it has be resolued

**Comment by joelemanoel** [comment]
Hi,

I have same problem. Edit code: https://github.com/BotoX/ServerStatus/blob/master/server/src/network.h not working.

Im sergate receive: (Wrong username and/or password.)

+30 servers

Any solution?
