### ISSUE TITLE
问一下是否可以根据分区的显示，现在是所有的盘的总量

### ISSUE THREAD

**Issue by baosi1234** [BotoX/ServerStatus#26]
问一下是否可以根据分区的显示，现在是所有的盘的总量

**Comment by kuretru** [comment]
1. 找到客户端的python文件
2. 找到`def get_hdd():`方法
3. 修改`p = subprocess.check_output(['df', '-Tlm', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'zfs', '-t', 'simfs', '-t', 'xfs']).decode("Utf-8")`代码

例如
`p = subprocess.check_output("df -Tlm --total -t ext4 | grep sda1",shell=True).decode("Utf-8")`
