### ISSUE TITLE
Cant start the daemon through service command

### ISSUE THREAD

**Issue by TheFonix** [BotoX/ServerStatus#31]
Hey!

When trying to run the daemon from sudo service serrate start i get

```
Failed to start sergate.service: Unit sergate.service not found.
```
Any idea? I've followed every step correctly, I'm running Ubuntu 16.04 

thanks!

**Comment by BotoX** [comment]
Do you have /etc/systemd/system/sergate.service ?
Try sudo systemctl daemon-reload and then sudo systemctl start sergate

**Comment by TheFonix** [comment]
I forgot to copy the sergate.service! Sorry about that!
