### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Yakashimoto** [BotoX/ServerStatus#33]
Hello,

the script completly dont work currently on Centos or Debian:

Server Script

Failed to start sergate.service: Unit sergate.service failed to load: No such file or directory.

than if start manually

![serverstatus](https://user-images.githubusercontent.com/35178136/34643952-bdf79c30-f32d-11e7-8bfc-eac625f98fae.png)

and the clients can also not connect...

whats wrong with this script currently?

**Comment by BotoX** [comment]
there's nothing wrong with it, you're just incompetent
read the README

**Comment by Yakashimoto** [comment]
i have read them..maybe you dont know what is written in the readme, because you also dont tell me what is wrong..dont be to supercilious, not all the people in the world have so much nerd skills as you!
