### ISSUE TITLE
Pre compiled exe?

### ISSUE THREAD

**Issue by IIPoliII** [BotoX/ServerStatus#44]
Hello is it possible to get the exe on the github repo i saw this issue but the guy didn't provided it https://github.com/BotoX/ServerStatus/issues/18

**Comment by Suleman-Elahi** [comment]
The link seems to be expired

**Comment by IIPoliII** [comment]
You can find a package here with the 3 files needed : http://scripts.poli.network/Github/ServerStatus/client.zip
Note that you need to put your config in client.cfg and then simply run it.
